#### 파이썬의 axis 이해

초보자(입문)으로 책을 필사 하다보면 이해가 안가도 일단 쓰고보고 넘어가는 일이 많았다. 하지만 하나씩 알고 넘어가자는 취지로 만들고 시작해본다.

- 참고사이트(http://machinelearningkorea.com/2019/05/18/%ED%8C%8C%EC%9D%B4%EC%8D%AC-axis-%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0-%EC%B9%98%ED%8A%B8%EC%BD%94%EB%93%9C/)

(**타이타닉의 생존자 가려내기**를 필사하면서 부터..)


파이썬 axis는 다른 언어에는 없는 기능으로, 대부분 행렬계산이 많이 일어나기 때문에 이를 지원한다..필요없어 보일때가 많지만, numpy행렬계산때는 유용하게 작동한다.




판다스를 사용하다 보면 평균 계산, 데이터프레임 열이나 행 삭제 작업등을 할 때 axis(축)을 지정해야 한다. 축을 넣어야 할 때면 0을 넣어야 하는지 1을 넣어야 하는지 헷갈릴 수 있다. 
 

-  aixs=0(index)은 행을 따라 동작합니다. 각 컬럼의 모든 행에 대해서 작용합니다.

-  aixs=1(columns)은 열을 따라 동작합니다. 각 행의 모든 컬럼에 대해서 작동합니다.



axis=0은 각 열의 모든 행에 대해서 동작합니다. 

  - drop 각 열의 행을 지운다

  - mean 각 열의 요소(행)들의 평균을 구한다.

  - rank 각 열의 요소(행)들의 순위를 구한다.

 

axis=1은 각 행의 모든 열에 대해서 동작합니다.

 - drop 각 행의 열을 지운다.

 - mean 각 행의  요소(열)들의 평균을 구한다.

 - rank 각 행의 요소(열)들의 순위를 구한다.




2차원의 행렬이 있다고 해보자.

In [3]:
import numpy as np

array = np.random.randint(10, size=(5,3)) 
array

array([[6, 4, 1],
       [4, 9, 0],
       [0, 9, 5],
       [9, 2, 8],
       [5, 2, 0]])

여기서 axis = 0은 무엇일까? 5,3 행렬에서 처음 5라고 생각하면되고, 다섯개의 원소를 죄다 더한다고 보면 된다.

In [4]:
np.sum(array, axis = 0)

array([24, 26, 14])

이차원의 데이터는 이해하기 쉬운데, 삼차원의 데이터도 이해해보자.

In [5]:
array3 = np.random.randint(10, size=(5,3,2)) 
array3

array([[[0, 6],
        [1, 7],
        [2, 6]],

       [[3, 3],
        [5, 9],
        [4, 4]],

       [[0, 0],
        [9, 9],
        [0, 9]],

       [[8, 9],
        [0, 2],
        [7, 4]],

       [[1, 5],
        [9, 1],
        [3, 6]]])

이제, 세가지의 데이터 방향이 있다. np.sum에서 axis = 0,1,2는 차례대로 5,3,2 데이터를 하나로 합쳐준다. 합계를 구하는 간단한 np.sum은 0은 5를 없애고 3,2를 남기고, 1은 3을, 2는 2를 없애고 나머지 차원을 살린다.

In [6]:
print(np.sum(array3, axis = 0))
print("")
print(np.sum(array3, axis = 0).shape)

[[12 23]
 [24 28]
 [16 29]]

(3, 2)


In [7]:
print(np.sum(array3, axis = 1))
print("")
print(np.sum(array3, axis = 1).shape)

[[ 3 19]
 [12 16]
 [ 9 18]
 [15 15]
 [13 12]]

(5, 2)


In [8]:
print(np.sum(array3, axis = 2))
print("")
print(np.sum(array3, axis = 2).shape)


[[ 6  8  8]
 [ 6 14  8]
 [ 0 18  9]
 [17  2 11]
 [ 6 10  9]]

(5, 3)
